# ==============================================================================
# Homelab Static Inventory
# ==============================================================================

[proxmox]
virt-1.iye.internal ansible_host=192.168.254.111 ansible_user=root
virt-2.iye.internal ansible_host=192.168.254.112 ansible_user=root
virt-3.iye.internal ansible_host=192.168.254.113 ansible_user=root

[docker_hosts]
docker-homelab.iye.internal ansible_host=192.168.254.164 ansible_user=rhoadsr ansible_become=true

[mikrotik]
switch-1.iye.internal ansible_host=switch-1.iye.internal ansible_network_os=community.routeros.routeros ansible_user=admin
switch-2.iye.internal ansible_host=switch-2.iye.internal ansible_network_os=community.routeros.routeros ansible_user=admin

[openwrt]
ap-outside.iye.internal ansible_host=192.168.0.41 ansible_user=root
ap-callie.iye.internal  ansible_host=192.168.0.42 ansible_user=root
ap-robert.iye.internal  ansible_host=192.168.0.44 ansible_user=root
ap-garage.iye.internal  ansible_host=192.168.0.45 ansible_user=root
ap-printer.iye.internal ansible_host=192.168.0.46 ansible_user=root
ap-fort.iye.internal    ansible_host=192.168.0.47 ansible_user=root

# Group Hierarchies
[linux:children]
proxmox
docker_hosts

[network:children]
mikrotik
openwrt

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
