---
# Homepage Header Widgets
# Reference: https://gethomepage.dev/configs/info-widgets/

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: medium
      hour12: true

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank
